spring:
  application.name: treinamento
  h2.console:
    enabled: true
    path: /h2-console
  datasource:
    username: sa
    password:
    platform: h2
    url: jdbc:h2:mem:testedb
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest